# Estos valores de General vienen fijados por ala app de bootstrap
general:
  cloudProvider: ""
  clusterName: ""
  environment: ""
  appName: "app-sonarqube"
  owner: ""
  appRegistry: ""
  internalDomain: ""
  appData: "{}"
sonarqube:
  postgresql:
    existingSecret: app-sonarqube-postgresql
  monitoringPasscode: false
  monitoringPasscodeSecretName: app-sonarqube-sonarqube-monitoring-passcode
  monitoringPasscodeSecretKey: SONAR_WEB_SYSTEMPASSCODE  
  sonarProperties: 
    sonar.log.level: INFO
ingress:
  host: "sonarq"
  path: "/"

