sonarqube:
  postgresql:
    existingSecret: app-sonarqube-postgresql
  monitoringPasscodeSecretName: app-sonarqube-sonarqube-monitoring-passcode
  monitoringPasscodeSecretKey: SONAR_WEB_SYSTEMPASSCODE
