{{ $name := .Values.general.appName }}
{{ $domain := .Values.general.internalDomain }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}.{{ $domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ $name }}-sonarqube
            port:
              number: 9000
        path: {{ .Values.ingress.path }}
        pathType: Prefix
