apiVersion: batch/v1
kind: Job
metadata:
  name: app-sonarqube-sonarqube-change-admin-password-hook
  labels:
    app: sonarqube
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: app-sonarqube-sonarqube-change-admin-password-hook
      labels:
        app: sonarqube
    spec:
      restartPolicy: OnFailure
      serviceAccountName: default
      containers:
      - name: app-sonarqube-sonarqube-change-default-admin-password
        image: curlimages/curl:latest
        command: ["sh", "-c", 'until curl -v --connect-timeout 100 app-sonarqube-sonarqube:9000/api/system/status | grep -w UP; do sleep 10; done; curl -v --connect-timeout 100 -u admin:$CURRENT_ADMIN_PASSWORD -X POST "app-sonarqube-sonarqube:9000/api/users/change_password?login=admin&previousPassword=$CURRENT_ADMIN_PASSWORD&password=$ADMIN_PASSWORD"']
        env:
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-sonarqube-admin-password
              key: password
        - name: CURRENT_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  app-sonarqube-admin-password
              key: currentPassword
        resources:
          limits:
            cpu: 800m
            memory: 4Gi
          requests:
            cpu: 400m
            memory: 2Gi
